//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostDeploymentTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PostDeploymentTools.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///    DECLARE @SqlStatement NVARCHAR(500)
        ///
        ///    IF NOT EXISTS (SELECT [LoginName] FROM SYSLOGINS WHERE [Name] = @UserName)
        ///    BEGIN
        ///        SET @SqlStatement = &apos;CREATE LOGIN [&apos; + @UserName + &apos;] FROM WINDOWS WITH DEFAULT_DATABASE=[&apos; + @DatabaseName + &apos;], DEFAULT_LANGUAGE=[us_english]&apos;
        ///        EXEC sp_executesql @SqlStatement
        ///    END
        ///
        ///    IF NOT EXISTS (SELECT [Name] FROM SYSUSERS WHERE [Name] = @UserName)
        ///    BEGIN
        ///        SET @SqlStatement = &apos;CREATE USER [&apos; + @UserName + &apos;] FOR LOGIN [&apos; + @Us [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///    DECLARE @SqlStatement NVARCHAR(500)
        ///
        ///    SET @SqlStatement = &apos;GRANT &apos; + @Permission + &apos; ON [&apos; + @SchemaName + &apos;].[&apos; + @ObjectName + &apos;] TO [&apos; + @UserName + &apos;]&apos;
        ///	EXEC sp_executesql @SqlStatement
        ///END.
        /// </summary>
        internal static string GrantObjectPermission {
            get {
                return ResourceManager.GetString("GrantObjectPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///    DECLARE @SqlStatement NVARCHAR(500)
        ///
        ///    SET @SqlStatement = &apos;GRANT &apos; + @Permission + &apos; ON SCHEMA::&apos; + @SchemaName + &apos; TO [&apos; + @UserName + &apos;]&apos;
        ///	EXEC sp_executesql @SqlStatement
        ///END.
        /// </summary>
        internal static string GrantSchemaPermission {
            get {
                return ResourceManager.GetString("GrantSchemaPermission", resourceCulture);
            }
        }
    }
}
